version: "3.5"

services:
  loki:
    image: grafana/loki:2.4.2
    ports:
      - "3100:3100"
    command: -config.file=/loki-config.yaml
    volumes:
      - loki-data:/loki
    configs:
      - loki-config.yaml

  promtail:
    image: grafana/promtail:2.4.1
    ports:
      - "1514:1514"
    volumes:
      - /var/log:/var/log
    configs:
      - promtail-config.yaml
    command: -config.file=/promtail-config.yaml

configs:
  loki-config.yaml:
    external: true
  promtail-config.yaml:
    external: true

volumes:
  loki-config:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=${NFS_HOST},rw,nfsvers=4
      device: ":${NFS_PATH}docker/loki/config"

  loki-data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=${NFS_HOST},rw,nfsvers=4
      device: ":${NFS_PATH}docker/loki/data"