version: '3.7'

volumes:
    tasmoadmin-data:
      driver: local
      driver_opts:
        type: "nfs"
        o: addr=${NFS_HOST},rw,nfsvers=4
        device: ":${NFS_PATH}tasmoadmin/data"

services:
  tasmoadmin:
    image: ghcr.io/tasmoadmin/tasmoadmin:latest
    ports:
      - 5555:80
    volumes:
      - tasmoadmin-data:/data

