---
version: '3.8'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    restart: always
    privileged: true
    volumes:
      - /data/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=Europe/Dublin
    devices:
      # Make sure this matched your adapter location
      # - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/zigbee
      - /dev/ttyUSB0:/dev/zigbee
 