version: '3.7'

volumes:
  unifi-config: 
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=${NFS_SERVER},rw,nfsvers=4
      device: ":${NFS_PATH}unifi/config"

services:
  unifi-controller:
    image: linuxserver/unifi-controller:latest
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M #optional
    volumes:
      - unifi-config:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure